name: Self-Heal Kamerta Runner

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Choose action: install or uninstall'
        required: true
        default: 'install'
        type: choice
        options:
          - install
          - uninstall
  schedule:
    - cron: '*/15 * * * *'
  workflow_run:
    workflows: ["CI", "Build", "Test"]
    types:
      - completed

jobs:
  kamerta-runner:
    if: github.event_name != 'workflow_dispatch' || github.event.inputs.action == 'install'
    runs-on: [kamerta]
    name: Install or Repair Kamerta Runner
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download DLX_Runner.ps1
        run: |
          Invoke-WebRequest -Uri "https://raw.githubusercontent.com/Dunker007/dunkerlux-shell/feature/self-heal-v0_3_1/bootstrap/DLX_Runner.ps1" -OutFile "$env:TEMP\DLX_Runner.ps1"

      - name: Execute DLX_Runner.ps1
        run: |
          $env:DLX_AUTOMATION_MODE = 'FULL'
          & "$env:TEMP\DLX_Runner.ps1"

  uninstall-runner:
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'uninstall'
    runs-on: [kamerta]
    name: Uninstall Kamerta Runner
    steps:
      - name: Stop and uninstall service
        run: |
          & "C:\DLXStudios\.runner\svc.cmd" stop
          & "C:\DLXStudios\.runner\svc.cmd" uninstall

      - name: Remove runner registration
        run: |
          $token = Read-Host "Paste fresh runner removal token"
          & "C:\DLXStudios\.runner\config.cmd" remove --token "$token"

      - name: Delete runner files
        run: |
          Remove-Item -Recurse -Force "C:\DLXStudios\.runner"
