name: Plesk Auto-Deploy (Fetch + Deploy)

on:
  push:
    branches:
      - deploy/coming-soon

permissions:
  contents: read

env:
  # Must be ONLY host or IP (no scheme, no port)
  PLESK_HOST: 74.208.158.134
  # Use the domain label EXACTLY as it appears in Plesk
  PLESK_DOMAIN: dlxstudios.ai
  # Use the repo name shown on the Plesk Git screen
  PLESK_REPO: dunkerlux-shell

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Show computed API endpoint (for debugging)
        run: |
          set -euo pipefail
          API="https://${PLESK_HOST}:8443/api/v2/cli/extension/call"
          echo "Plesk CLI API endpoint -> ${API}"

      - name: Probe repo info in Plesk (git --info)
        run: |
          set -euo pipefail
          API="https://${PLESK_HOST}:8443/api/v2/cli/extension/call"
          curl -sS -k --fail-with-body -X POST "$API" \
            -H "X-API-Key: ${{ secrets.plesk_api }}" \
            -H "Content-Type: application/json" \
            --data-raw @- <<'JSON'
          {
            "params": [
              "--exec","git",
              "--info",
              "-domain","${PLESK_DOMAIN}",
              "-name","${PLESK_REPO}"
            ]
          }
          JSON
      - name: Fetch latest commits into Plesk (git --fetch)
        run: |
          set -euo pipefail
          API="https://${PLESK_HOST}:8443/api/v2/cli/extension/call"
          curl -sS -k --fail-with-body -X POST "$API" \
            -H "X-API-Key: ${{ secrets.plesk_api }}" \
            -H "Content-Type: application/json" \
            --data-raw @- <<'JSON'
          {
            "params": [
              "--exec","git",
              "--fetch",
              "-domain","${PLESK_DOMAIN}",
              "-name","${PLESK_REPO}"
            ]
          }
          JSON
      - name: Deploy to /httpdocs (git --deploy)
        run: |
          set -euo pipefail
          API="https://${PLESK_HOST}:8443/api/v2/cli/extension/call"
          curl -sS -k --fail-with-body -X POST "$API" \
            -H "X-API-Key: ${{ secrets.plesk_api }}" \
            -H "Content-Type: application/json" \
            --data-raw @- <<'JSON'
          {
            "params": [
              "--exec","git",
              "--deploy",
              "-domain","${PLESK_DOMAIN}",
              "-name","${PLESK_REPO}"
            ]
          }
          JSON

      - name: Log last commit (optional)
        continue-on-error: true
        run: |
          API="https://${PLESK_HOST}:8443/api/v2/cli/extension/call"
          curl -sS -k -X POST "$API" \
            -H "X-API-Key: ${{ secrets.plesk_api }}" \
            -H "Content-Type: application/json" \
            --data-raw @- <<'JSON'
          {
            "params": [
              "--exec","git",
              "--get-last-commit",
              "-domain","${PLESK_DOMAIN}",
              "-name","${PLESK_REPO}"
            ]
          }
          JSON
