name: DLX Production Deploy (main → deploy/coming-soon)

on:
  push:
    branches: [ "main" ]      # deploy whenever main changes
  workflow_dispatch: {}        # allow manual runs

permissions:
  contents: write

concurrency:
  group: dlx-prod-deploy
  cancel-in-progress: true

jobs:
  deploy:
    name: Sync site to deploy/coming-soon
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo (required)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false  # we push via URL token

      - name: Sanity check (verify git repo present)
        run: |
          pwd
          ls -la
          git rev-parse --is-inside-work-tree

      - name: Configure Git identity (bot)
        run: |
          git config user.name "dlx-deployer"
          git config user.email "actions@users.noreply.github.com"

      # --- OPTIONAL BUILD STEP (uncomment if you build) ---
      # - name: Build site
      #   run: |
      #     npm ci
      #     npm run build
      #   # If you build, set RSYNC_SRC below to your build output dir (e.g., "$GITHUB_WORKSPACE/dist")

      - name: Prepare deploy worktree
        id: prep
        run: |
          set -e
          DEPLOY_BRANCH="deploy/coming-soon"
          WORKTREE_DIR="$(mktemp -d)"
          echo "worktree=${WORKTREE_DIR}" >> $GITHUB_OUTPUT
          echo "branch=${DEPLOY_BRANCH}" >> $GITHUB_OUTPUT
          # If the remote branch exists, fetch it and create a local branch to base the worktree on.
          if git ls-remote --exit-code --heads origin "${DEPLOY_BRANCH}" >/dev/null 2>&1; then
            echo "Remote branch exists; fetching and creating local branch '${DEPLOY_BRANCH}'."
            git fetch origin "${DEPLOY_BRANCH}:${DEPLOY_BRANCH}"
            git worktree add "${WORKTREE_DIR}" "${DEPLOY_BRANCH}"
          else
            echo "Remote branch does not exist; creating from HEAD."
            git worktree add -B "${DEPLOY_BRANCH}" "${WORKTREE_DIR}" HEAD
          fi

          echo "SYNC_START=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV
          echo "SRC_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Sync site files (exclude CI files)
        env:
          WORKTREE_DIR: ${{ steps.prep.outputs.worktree }}
        run: |
          set -e
          # If you build, set RSYNC_SRC to your build output dir (e.g., "$GITHUB_WORKSPACE/dist")
          RSYNC_SRC="$GITHUB_WORKSPACE"
          RSYNC_DEST="$WORKTREE_DIR"
          rsync -av --delete \
            --exclude ".git/" \
            --exclude ".github/" \
            --exclude ".gitignore" \
            --exclude "README.md" \
            --exclude "LICENSE" \
            "$RSYNC_SRC"/ "$RSYNC_DEST"/

      - name: Commit deploy snapshot
        env:
          WORKTREE_DIR: ${{ steps.prep.outputs.worktree }}
        run: |
          set -e
          cd "$WORKTREE_DIR"
          if git status --porcelain | grep .; then
            git add -A
            git commit -m "deploy: sync from main @ ${SRC_SHA} on ${SYNC_START} [skip ci]"
          else
            echo "No changes to deploy"
          fi

      - name: Push to deploy branch (GITHUB_TOKEN)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          DEPLOY_BRANCH: ${{ steps.prep.outputs.branch }}
          WORKTREE_DIR: ${{ steps.prep.outputs.worktree }}
        run: |
          set -e
          cd "$WORKTREE_DIR"
          git push "https://x-access-token:${GITHUB_TOKEN}@github.com/${REPO}.git" HEAD:${DEPLOY_BRANCH}

      - name: Cleanup worktree
        if: always()
        env:
          WORKTREE_DIR: ${{ steps.prep.outputs.worktree }}
        run: |
          set -e
          if [ -d "$WORKTREE_DIR/.git" ]; then
            git worktree remove -f "$WORKTREE_DIR"
          else
            echo "Worktree was not fully created; nothing to clean."
          fi
